/* Generated by tools/gen_assets.py, do not edit. */
#ifndef TETRIS_ASSETS_H
#define TETRIS_ASSETS_H
#include <stdint.h>

#define ASSET_TILE   15U   /* tile edge in pixels */
#define ASSET_BG_W   150U
#define ASSET_BG_H   330U

/* One glyph of an anti-aliased font. The bitmap is width x the
 * font height, one coverage byte per pixel, row major. xoff is
 * where the bitmap starts relative to the pen position, advance
 * is how far the pen moves on. */
typedef struct {
    uint32_t offset;   /* into the font's bitmap array */
    int8_t   xoff;
    uint8_t  width;
    uint8_t  advance;
} asset_glyph_t;

typedef struct {
    const uint8_t       *bitmap;
    const asset_glyph_t *glyph;   /* FIRST..LAST char */
    uint8_t              height;
    uint8_t              baseline; /* from the top of the box */
} asset_font_t;

#define ASSET_FONT_FIRST  32
#define ASSET_FONT_LAST   126

/* ARGB8888, index 0..6 = colour 1..7 of the game (I J L O S T Z). */
extern const uint32_t asset_tile[7][ASSET_TILE * ASSET_TILE];
extern const uint32_t asset_tile_flash[7][ASSET_TILE * ASSET_TILE];
/* Grey level per pixel, blended over the field with a variable alpha. */
extern const uint8_t  asset_tile_ghost[ASSET_TILE * ASSET_TILE];
/* Grey level per pixel of the whole 10x22 tile field. */
extern const uint8_t  asset_bg[ASSET_BG_H * ASSET_BG_W];

extern const asset_font_t font_small;   /* DejaVu Sans Bold 10 px */
extern const asset_font_t font_big;   /* DejaVu Sans Bold 14 px */
extern const asset_font_t font_huge;   /* DejaVu Sans Bold 19 px */

#endif /* TETRIS_ASSETS_H */
